### ISSUE TITLE
Web project missing libSkiaSharp

### ISSUE THREAD

**Issue by k-karuna** [wieslawsoltes/Draw2D#34]
After cloning and starting Draw2D.Web on macOS (via Rider) i'm getting this error in browser console:

```
Unhandled Exception:
System.DllNotFoundException: libSkiaSharp
at SkiaSharp.SKFont..ctor()
at Avalonia.Skia.PlatformRenderInterface..cctor() in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 198
Unhandled exception rendering component: The type initializer for 'Avalonia.Skia.PlatformRenderInterface' threw an exception.
System.TypeInitializationException: The type initializer for 'Avalonia.Skia.PlatformRenderInterface' threw an exception.
 ---> System.DllNotFoundException: libSkiaSharp
```

<img width="661" alt="image" src="https://user-images.githubusercontent.com/5014045/154696697-102b9c2f-73ec-4d93-abeb-f15867dcee67.png">
 
May be you have faced this issue and know how to resolve this?
Do you start your WebApp during development? Or you develop app looking on desktop version and web is just compiling after things done?

**Comment by k-karuna** [comment]
It seems the problem is solved by
`dotnet workload install wasm-tools`
